apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-act-runner-config
  namespace: gitea
data:
  config.yaml: |
    runner:
      labels:
        - "ubuntu-latest:docker://gitea.local:3000/superadmin/runner-images/ubuntu:act-latest"
        - "ubuntu-24.04:docker://gitea.local:3000/superadmin/runner-images/ubuntu:act-latest"
        - "ubuntu-22.04:docker://gitea.local:3000/superadmin/runner-images/ubuntu:act-latest"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-act-runner
  namespace: gitea
spec:
  serviceName: gitea-act-runner
  replicas: 2
  selector:
    matchLabels:
      app: gitea-act-runner
  template:
    metadata:
      labels:
        app: gitea-act-runner
    spec:
      containers:
        - name: runner
          image: gitea/act_runner:latest
          imagePullPolicy: IfNotPresent
          command:
            - act_runner
          args:
            - daemon
            - --config
            - /config/config.yaml
          env:
            - name: GITEA_INSTANCE_URL
              valueFrom:
                secretKeyRef:
                  name: gitea-runner-secret
                  key: GITEA_INSTANCE_URL
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-runner-secret
                  key: GITEA_RUNNER_REGISTRATION_TOKEN
            - name: GITEA_RUNNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          volumeMounts:
            - name: runner-data
              mountPath: /data
            - name: runner-config
              mountPath: /config
              readOnly: true

        - name: docker-dind
          image: docker:27-dind
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --insecure-registry=gitea.local:3000
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker

      volumes:
        - name: dind-storage
          emptyDir: {}
        - name: runner-config
          configMap:
            name: gitea-act-runner-config

  volumeClaimTemplates:
    - metadata:
        name: runner-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
