apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aCiDcHaOZ/k3s-argo.git
    targetRevision: main
    path: apps/gitea

  destination:
    server: https://kubernetes.default.svc
    namespace: gitea

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

env:
  - name: GITEA__server__ROOT_URL
    value: "http://gitea.local:3000/
  - name: GITEA__server__DOMAIN
    value: "gitea.local"
  - name: GITEA__server__HTTP_PORT
    value: "3000"
  - name: GITEA__server__PROTOCOL
    value: "http"
