namespace: semaphore

replicaCount: 1

strategy:
  type: Recreate

image:
  repository: gitea.local:30080/superadmin/semaphore-plus
  tag: latest
  pullPolicy: Always

semaphore:
  publicUrl: http://semaphore.local
  dbDialect: bolt
  admin: {}

persistence:
  storageClass: longhorn-static
  size: 5Gi
  accessMode: ReadWriteOnce

security:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  fixPermissions: true

service:
  name: semaphore-web
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  host: semaphore.local
