apiVersion: v1
kind: ServiceAccount
metadata:
  name: semaphore
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: semaphore-job-runner
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]

  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: semaphore-job-runner
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: semaphore
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: semaphore-job-runner
  apiGroup: rbac.authorization.k8s.io
