---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: semaphore-orange-kuma-cleaner
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - persistentvolumeclaims
      - pods
    verbs: ["get", "list", "watch", "delete"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: semaphore-orange-kuma-cleaner
subjects:
  - kind: ServiceAccount
    name: semaphore
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: semaphore-orange-kuma-cleaner
  apiGroup: rbac.authorization.k8s.io
